
apiVersion: batch/v1
kind: Job
metadata:
  name: gatling-test-job
spec:
  template:
    spec:
      containers:
      - name: gatling
        image: image-registry.openshift-image-registry.svc:5000/redwan-alabed91-dev/gatling-demo-v-3-git:latest
        command: ["/opt/gatling/gatling/bin/gatling.sh", "-s", "computerdatabase.BasicSimulation"]
        volumeMounts:
        - name: results
          mountPath: /opt/gatling/gatling/results  # Mount the results directory
      restartPolicy: Never
      volumes:
      - name: results
        persistentVolumeClaim:  # Use a PVC to store results
          claimName: gatling-results-pvc
